version: "3.9"

services:
  backend:
    build: ./job_craft_backend
    container_name: jobcrafto-backend
    ports:
      - "2005:2005"
    networks:
      - jobcrafto-network
    restart: always

  frontend:
    build: ./job-craft-frontend/job-craft-frontend
    container_name: jobcrafto-frontend
    ports:
      - "3000:80"  # host:container
    depends_on:
      - backend
    networks:
      - jobcrafto-network
    restart: always

networks:
  jobcrafto-network:
    driver: bridge
