apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: jobcrafto
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080       # cluster port
      targetPort: 8080 # container port
  type: ClusterIP
