name: Build and Push Frontend + Backend Images

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------------- FRONTEND ------------------
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./job-craft-frontend/job-craft-frontend
          file: ./job-craft-frontend/job-craft-frontend/Dockerfile
          push: true
          tags: |
            athukuribhavya/frontend:latest
            athukuribhavya/frontend:${{ github.sha }}

      # ---------------- BACKEND -------------------
      - name: Give execute permission to mvnw
        run: chmod +x mvnw
        working-directory: job_craft_backend

      - name: Build backend JAR
        run: ./mvnw clean package -DskipTests
        working-directory: job_craft_backend

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./job_craft_backend
          file: ./job_craft_backend/Dockerfile
          push: true
          tags: |
            athukuribhavya/backend:latest
            athukuribhavya/backend:${{ github.sha }}
